### PR TITLE
activity tracking in node SDK

### PR DESCRIPTION
**Pull request by vasani-arpit**

### CODE REVIEW

**Comment by vasani-arpit** [comment]
After generating the build in `src/node`, add the following lines to an express based application
```js
 const Mok = require('src/node/dist/node.cjs');
 const { useMokExpress } = Mok.middleware;
 
 useMokExpress(
   app, //Pass the express instance
   Mok.init({
     readKey: "<READ_KEY>",
     writeKey: "<WRITE_KEY>",
     callback: function (data){
       console.log(data); // optional callback function to trace events
     },
     setUser: function (){
       return "<USER ID>"; // function to set user ID for each activity. Return type can be string or Promise<string>
     }
   })
 );
 ```

**Comment by abhay-singh-au3** [comment]
After importing to an express application getting errors

import line - `const Mok = require('@mok.one/sdk/node');`

error - ` Package subpath './node/node.cjs' is not defined by "exports"`

**Comment by joysonjoy1811** [comment]
> After importing to an express application getting errors
> 
> import line - `const Mok = require('@mok.one/sdk/node');`
> 
> error - ` Package subpath './node/node.cjs' is not defined by "exports"`

I've added the node export references to package.json. It shouldn't give that error now @abhay-singh-au3

**Comment by abhay-singh-au3** [comment]
```js
setUser: function (req) { // We will pass on req parameter, so that developers can add their custom logic
 return req['Headers'].client_id; // This will be custom logic added by developers
}
```

**Comment by joysonjoy1811** [comment]
> ```js
> setUser: function (req) { // We will pass on req parameter, so that developers can add their custom logic
>  return req['Headers'].client_id; // This will be custom logic added by developers
> }
> ```

It is added now @abhay-singh-au3

**Pull request merged**
